config/routes.rb
Rails.application.routes.draw do
  if defined? Debugbar
    mount Debugbar::Engine => Debugbar.config.prefix
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  get "my" => "my#index"

  delete "my/delete_account" => "my#delete_account"

  resources :posts do
    resources :comments, only: :create
    resource :like, only: [:create, :destroy]
  end

  resources :likes, only: :create

  mount API => '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  multi_tenant :tenant

  belongs_to :user
  belongs_to :post

  validates :user, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  multi_tenant :tenant

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  multi_tenant :tenant

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  include ActiveRecord::Bitemporal

  validates :title, presence: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  multi_tenant :tenant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked?(post)
    likes.exists?(post: post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :password, :password_confirmation, :name ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[create]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      redirect_to @post, alert: 'Comment was not created.'
    end
  end

  private

  def set_comment
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  set_current_tenant_through_filter # Required to opt into this behavior

  def index
    Rails.cache.write('foo', 'bar')
    @cached_value = Rails.cache.read('foo')
    Rails.logger.info("Cached value: #{@cached_value}")

    ExampleJob.perform_later
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @like = @post.likes.build(user: current_user)

    if @like.save
      redirect_to @post, notice: 'You liked this post.'
    else
      redirect_to @post, alert: 'Unable to like this post.'
    end
  end

  def destroy
    @like = @post.likes.find_by(user: current_user)

    if @like.destroy
          redirect_to @post, notice: 'You unliked this post.'
    else
      redirect_to @post, alert: 'Unable to unlike this post.'
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  before_action :authenticate_user!
  set_current_tenant_through_filter # Required to opt into this behavior
  before_action :set_tenant_as_tenant

  def set_tenant_as_tenant
    tenant = Tenant.find(current_user.tenant_id)
    set_current_tenant(tenant)
  end

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]
  set_current_tenant_through_filter # Required to opt into this behavior
  before_action :set_tenant_as_tenant

  def set_tenant_as_tenant
    tenant = Tenant.find(current_user.tenant_id)
    set_current_tenant(tenant)
  end

  def index
    @posts = Post.preload(:comments)
    @all_posts = Post.ignore_valid_datetime
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to post_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<p>Welcome to sandbox-rails-multi-tenant-architecture.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SandboxRailsMultiTenantArchitecture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= debugbar_head  if defined? Debugbar %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
    <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :get %>
    </li>
    <li>
        <%= link_to "My Page", my_path %>
    </li>
    <li>
        <%= link_to "Posts", posts_path %>
    </li>
    <% else %>
    <li>
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
    <li>
      <%= link_to "Sign In", new_user_session_path %>
    </li>
    <% end %>

    <%= yield %>
    <%= debugbar_body if defined? Debugbar %>
  </body>
</html>

app/views/my/index.html.erb
<h1>My Page</h1>
<p>You're loggined as <%= current_user.name %></p>
<p>You're  tenant is <%= current_user.tenant.name %></p>

<%= link_to "Edit your user info", edit_user_registration_path %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Update Post" %>
  </div>
<% end %>

<%= link_to 'Back', @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= link_to 'New Post', new_post_path %>
<h2>List</h2>
<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <p><%= post.content %></p>
  <!-- コメントを表示するコードを追加 -->
  <% post.comments.includes(:user).each do |comment| %>
    <p><strong><%= comment.user.name %>:</strong> <%= comment.content %></p>
  <% end %>
<% end %>

<h2>History</h2>
<% @all_posts.each do |post| %>
  <h2><%= link_to post.title, post %></h2>
  <p><%= post.content %></p>
  <p>
    <span>valid_from<%= post.valid_from %></span>
    <span>valid_to<%= post.valid_from %></span>
    <span>transaction_from<%= post.valid_from %></span>
    <span>transaction_to<%= post.valid_from %></span>
  </p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, name: "title", id: "session_title" %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, name: "content", id: "session_content" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Post" %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<% if current_user == @post.user %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%# FIXME: turboの都合なのかなぜか機能しない %>
  <%= link_to 'Delete', post_path(@post), method: :delete %>
<% end %>

<% if current_user.liked?(@post) %>
  <%= button_to 'Unlike', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'Like', post_like_path(@post) %>
<% end %>

<%= form_with model: [@post, @post.comments.build], local: true do |form| %>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<% if @post.comments.exists? %>
  <% @post.comments.each do |comment| %>
    <%# FIXME: comment.user.inspectしてみると　なぜか空のオブジェクトが余分に追加されてしまう。%>
    <% if comment.user.present? %>
    <p><strong><%= comment.user.name %>:</strong> <%= comment.content %></p>
    <% end %>
  <% end %>
<% else %>
  <p><strong>Unknown User:</strong> No comments yet.</p>
<% end %>
<%= link_to 'Back', posts_path %>